substitutions:
  hostname: "pir-tuywe3s-module-esp8266" 
  #password_ota: ""
  #key_api: ""
  installation_area: "дом - "
  wifi_ssid: !secret wifi_ssid_house_hall
  wifi_password: !secret wifi_password_n
  static_ip: 192.168.100.191
  board: "board-tuya-tuwe3s"
  device_http: "pir"
  publish_message: Зарядить аккумулятор


packages:  
  - !include device/pir-water-leak-uart-tuya-mqtt/house-bathhouse.yaml